name: Hello World Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  hello:
    runs-on: self-hosted
    steps:
      - name: Say hello
        run: echo "Hello from my self-hosted runner!"
      
      - name: Show system info
        run: |
          echo "Running on: $(hostname)"
          echo "Current user: $(whoami)"
          echo "Date: $(date)"
