name: Matrix Build
on: [push]
jobs:
  test:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [16, 18, 20]
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node ${{ matrix.node-version }}
        run: echo "Testing with Node ${{ matrix.node-version }}"
      - run: npm ci
      - run: npm test
