name: Multi-Job Pipeline
on: [push]
jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - run: npm test
  build:
    needs: test
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - run: npm run build
  deploy:
    needs: [test, build]
    runs-on: self-hosted
    if: github.ref == 'refs/heads/main'
    steps:
      - run: echo "Deploying application"
