name: Testing Pipeline
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      
      - name: Check for secrets
        run: ./check_secrets.sh
      
      - name: Build Docker image
        run: docker build -t test-app .
      
      - name: Start application
        run: docker run -d --name test-container -p 3000:3000 test-app
      
      - name: Wait for app to start
        run: sleep 5
      
      - name: Run tests
        run: node test_app.js
      
      - name: Cleanup
        if: always()
        run: docker stop test-container && docker rm test-container
